src/apps/blog/urls.py
from django.urls import path
from .views import HomeView, ServicesView
from apps.core.views import Error404View

app_name = 'blog'

urlpatterns = [

    path('', HomeView.as_view(), name='home'),
    path('servicios/',
         ServicesView.as_view(),
         name='servicios'),
    path('404/',
         Error404View.as_view(),
         name='error-404'),

]

src/urls.py
from django.contrib import admin
from django.conf.urls import include, handler404
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from apps.core.views import Error404View

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.blog.urls')),
    path('user/', include('apps.userprofile.urls')),
    path('api/v1.0/', include('apps.blog.rest')),
    ]

handler404 = Error404View.as_view()
print("settingsDebug", settings)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/web/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <title>Finniu</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="La mejor forma de invertir tu dinero" />
        <meta name="keywords" content="HTML, CSS, JavaScript, Python, Blog" />
        <meta name="author" content="Diego Delavega" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
        <link href='https://fonts.googleapis.com/css?family=Poppins:200,400,500,700,800&display=swap' rel='stylesheet' type='text/css'>                     
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css" />
        <script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
        <link href='https://fonts.googleapis.com/css?family=Poppins:200,400,500,700,800&display=swap' rel='stylesheet' type='text/css'>                     
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
        <!--[if lt IE 9]>
            <script src="js/html5shiv.js"></script>            
            <script src="js/respond.min.js"></script>                   
        <![endif]-->                
    </head>
    
  <body class="one-page"> 
    {% include "web/header.html" %}



        
        
        {% block content %}
        
        {% endblock content %}


    {% include "web/footer.html" %}
      <!--=================== SCRIPT ===================-->

  </body>
</html>

src/templates/web/footer.html
{% load static %}

  <!-- ================= FOOTER ================= -->
  
    

  

 
<footer class="p-4 bg-white rounded-lg shadow md:px-6 md:py-8 dark:bg-gray-900">
    <div class="sm:flex sm:items-center sm:justify-around">
        <div class="grid grid-cols-1 gap-8 py-8 px-6 md:grid-cols-1">
            <a href="" class="flex items-center mb-4 sm:mb-0">
                <img src="{% static 'images/LogoAzul.png' %}" class="mr-3" alt="Finniu Logo" />
            </a>
            <div class="grid grid-cols-1 gap-8 px-12 md:grid-cols-1">
                <ul class="text-gray-600 dark:text-gray-400">
                    <li>
                        <a href="#" class="mr-4 hover:underline md:mr-6 ">Teléfono: 963 993 305</a>
                    </li>
                    <li>
                        <a href="#" class="mr-4 hover:underline md:mr-6">Correo: hola@finniu.com</a>
                    </li>
                    <li>
                        <a href="#" class="mr-4 hover:underline md:mr-6 ">Oficina: Av San Luis 2076, Oficina 302. San Borja</a>
                    </li>

                </ul>
            </div>
            
        </div>
        <div class="grid grid-cols-1 gap-8 px-12 md:grid-cols-1">
            <ul class="text-gray-600 dark:text-gray-400">
                <li class="mr-4 md:mr-6 ">También encuentranos en nuestras redes sociales
                </li>
                <li class="flex">
                    <div>
                        <svg width="28" height="25" viewBox="0 0 37 36" fill="none" xmlns="http://www.w3.org/2000/svg" class="inline">
                            <g clip-path="url(#clip0_504_1040)">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8.40234 3.78756C9.38176 3.41676 10.5033 3.16356 12.1445 3.09084C13.7893 3.01692 14.3152 3 18.502 3C22.6889 3 23.2144 3.01812 24.8582 3.09084C26.4983 3.16236 27.6192 3.41676 28.6005 3.78756C29.6129 4.17048 30.4736 4.68288 31.3303 5.51772C32.187 6.35256 32.7139 7.1886 33.1086 8.17488C33.4897 9.1278 33.75 10.2188 33.8247 11.8158C33.8994 13.4152 33.9168 13.9265 33.9168 18C33.9168 22.0735 33.8994 22.5836 33.8247 24.1842C33.7512 25.781 33.4897 26.8716 33.1086 27.8251C32.7139 28.8114 32.1884 29.6488 31.3303 30.4823C30.4722 31.3158 29.6129 31.8284 28.5992 32.2124C27.6192 32.5832 26.4984 32.8364 24.857 32.9092C23.2132 32.9831 22.6876 33 18.5008 33C14.3139 33 13.7893 32.9819 12.1445 32.9092C10.5033 32.8364 9.38361 32.5832 8.40234 32.2124C7.388 31.8284 6.5292 31.3154 5.67126 30.4823C4.81332 29.6491 4.28654 28.8114 3.89296 27.8251C3.51185 26.8716 3.25161 25.7812 3.17686 24.1842C3.10089 22.5848 3.0835 22.0735 3.0835 18C3.0835 13.9265 3.10089 13.4152 3.17686 11.8158C3.25161 10.219 3.51185 9.1284 3.89296 8.17488C4.28654 7.188 4.81319 6.35124 5.67126 5.51772C6.52932 4.6842 7.388 4.17048 8.40234 3.78756ZM18.4992 11.3C14.6632 11.3 11.5918 14.3205 11.5918 18C11.5918 21.6795 14.6632 24.7 18.4992 24.7C22.3355 24.7 25.4085 21.6792 25.4085 18C25.4085 14.3208 22.3355 11.3 18.4992 11.3ZM9.99183 18C9.99183 13.3962 13.8208 9.7 18.4992 9.7C23.1774 9.7 27.0085 13.3959 27.0085 18C27.0085 22.6041 23.1774 26.3 18.4992 26.3C13.8208 26.3 9.99183 22.6038 9.99183 18ZM18.2502 7C18.9405 7 19.5002 6.44036 19.5002 5.75C19.5002 5.05964 18.9405 4.5 18.2502 4.5C17.5598 4.5 17.0002 5.05964 17.0002 5.75C17.0002 6.44036 17.5598 7 18.2502 7Z" fill="#0D3A5C"/>
                            </g>
                            <defs>
                            <clipPath id="clip0_504_1040">
                            <rect width="37" height="36" fill="white"/>
                            </clipPath>
                            </defs>
                        </svg>                    
                        <a href="https://www.instagram.com/finniu.pe/" class="ml-2 hover:underline md:ml-2">finniu.pe</a>
                    </div>
                    
                </li>
                <li>
                    <div>
                        <svg width="28" height="25" viewBox="0 0 41 38" fill="none" xmlns="http://www.w3.org/2000/svg" class="inline">
                            <path d="M25.8805 13.2914C24.5711 13.2872 23.2737 13.522 22.0626 13.9823C20.8514 14.4426 19.7502 15.1194 18.8219 15.9739C17.8937 16.8285 17.1567 17.844 16.653 18.9624C16.1494 20.0808 15.889 21.2801 15.8867 22.4917V31.7868C15.8867 32.1642 16.0487 32.526 16.337 32.7929C16.6254 33.0597 17.0164 33.2096 17.4242 33.2096H21.0117C21.4195 33.2096 21.8106 33.0597 22.0989 32.7929C22.3872 32.526 22.5492 32.1642 22.5492 31.7868V22.4917C22.5489 22.0608 22.6467 21.6346 22.8363 21.241C23.0259 20.8474 23.3029 20.4952 23.6495 20.2073C23.996 19.9195 24.4043 19.7024 24.8475 19.5703C25.2908 19.4382 25.7592 19.3941 26.2221 19.4407C27.0524 19.5375 27.8154 19.9128 28.3665 20.4956C28.9175 21.0784 29.2183 21.828 29.2117 22.6023V31.7868C29.2117 32.1642 29.3737 32.526 29.662 32.7929C29.9504 33.0597 30.3414 33.2096 30.7492 33.2096H34.3367C34.7445 33.2096 35.1356 33.0597 35.4239 32.7929C35.7122 32.526 35.8742 32.1642 35.8742 31.7868V22.4917C35.872 21.2801 35.6116 20.0808 35.1079 18.9624C34.6043 17.844 33.8672 16.8285 32.939 15.9739C32.0108 15.1194 30.9096 14.4426 29.6984 13.9823C28.4872 13.522 27.1898 13.2872 25.8805 13.2914Z" fill="#0D3A5C"/>
                            <path d="M11.275 14.7133H6.6625C5.81336 14.7133 5.125 15.3502 5.125 16.136V31.786C5.125 32.5717 5.81336 33.2087 6.6625 33.2087H11.275C12.1241 33.2087 12.8125 32.5717 12.8125 31.786V16.136C12.8125 15.3502 12.1241 14.7133 11.275 14.7133Z" fill="#0D3A5C"/>
                            <path d="M8.96875 11.8691C11.0916 11.8691 12.8125 10.2763 12.8125 8.31161C12.8125 6.34688 11.0916 4.75415 8.96875 4.75415C6.84591 4.75415 5.125 6.34688 5.125 8.31161C5.125 10.2763 6.84591 11.8691 8.96875 11.8691Z" fill="#0D3A5C"/>
                        </svg>
                        <a href="https://pe.linkedin.com/company/finniu?original_referer=https%3A%2F%2Fwww.google.com%2F" class="ml-2 hover:underline md:ml-2">Finniu</a>
                    </div>
                </li>

            </ul>
        </div>
        
    </div>
    <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
    <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">Finniu © 2022 | Todos los derechos reservados
    </span>
</footer>


  
  
  
  
<!-- =============== FOOTER END =============== -->

src/templates/web/header.html
{% load static %}

  <!-- ================= HEADER ================= -->
<nav class="px-2 sm:px-4 py-2.5 fixed w-full z-50 top-0 left-0 border-gray-200 nav-sticky">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="" class="flex items-center">
        <img src="{% static 'images/LogoCrema.png' %}" class="mr-3 h-4-5 logo1" alt="Finniu Logo">
        <img src="{% static 'images/LogoAzul.png' %}" class="mr-3 h-4-5 logo2 hidden" alt="Finniu Logo">
    </a>
    <div class="flex md:order-2">
      <a class="btn-sticky text-color-blue background-celeste hover:bg-cyan-300 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 "
      href="https://app.finniu.com/" target="_blank">Registrate</a>
      <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 " aria-controls="navbar-sticky" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
      <div class="hidden  md:flex md:justify-end md:flex-auto  text-white navbar-default" id="navbar-sticky">
        <ul class="flex flex-col p-4 mt-4 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 ">
          <li>
            <a href="{% url 'blog:home' %}" class="block py-2 pr-4 pl-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 ">Home</a>
          </li>

          <li>
            <a href="{% url 'blog:servicios' %}" class="block py-2 pr-4 pl-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 ">Servicios</a>
          </li>

          <li>
            <a href="https://finantips.substack.com/" class="block py-2 pr-4 pl-3rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 ">Blogs</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script>
      $(document).scroll(function () {
        var $nav = $(".nav-sticky");
        var $logo1 = $(".logo1");
        var $logo2 = $(".logo2");
        var $head = $(".navbar-default");
        var $btn_sticky = $(".btn-sticky");
        $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
        $logo1.toggleClass('hidden', $(this).scrollTop() > $nav.height());
        $logo2.toggleClass('hidden', $(this).scrollTop() < $nav.height());
        $head.toggleClass('text-color-blue', $(this).scrollTop() > $nav.height());
        $btn_sticky.toggleClass('button-sticky', $(this).scrollTop() > $nav.height());
        
      });

  </script>
  
  
<!-- =============== HEADER END =============== -->